import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
const root='/Users/minliny/Documents/Reader/Reader-for-HarmonyOS/entry/src/main/ets/';
const clean=s=>s.replace(/^import[\s\S]*?;\n/gm,'');
const load=async names=>import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(names.map(n=>clean(readFileSync(root+n,'utf8'))).join('\n'))).toString('base64'));
const {SourceSwitchGateway}=await load(['app/ErrorMessage.ts','features/common/BookAcquisitionPresentation.ts','features/common/CachedBookIdentity.ts','features/source/ReaderSourceCategory.ts','features/source/SourceSwitchGateway.ts']);
let release;const slow=new Promise(r=>release=r);const called=[];
const g=new SourceSwitchGateway({request:async()=>({data:{sources:Array.from({length:9},(_,i)=>({sourceId:'s'+i,name:'源'+i,enabled:true}))}})});
g.discoverFromSource=async(_,__,___,source)=>{called.push(source.sourceId);if(source.sourceId==='s0')await slow;return[];};
const running=g.discoverCandidates('origin','book','鸣龙');
await new Promise(r=>setTimeout(r,0));
assert.equal(called.length,8);assert(!called.includes('s8'));
console.log(JSON.stringify({probe:'actual SourceSwitchGateway.discoverCandidates',beforeSlowRelease:called.slice(),ninthSourceDispatched:false,conclusion:'Eight-source batch barrier holds next source despite seven completed source operations'}));
release();await running;assert.equal(called.length,9);
const {classifyReaderSource}=await load(['features/source/ReaderSourceCategory.ts']);
console.log(JSON.stringify({probe:'actual classifyReaderSource',namedBaiduPicture:classifyReaderSource({bookSourceType:0,name:'百度图片（优）'}),unlabelledImageSource:classifyReaderSource({bookSourceType:0,name:'默认',baseUrl:'https://image.baidu.com/'})}));
const {SearchGateway}=await load(['app/ErrorMessage.ts','features/source/ReaderSourceCategory.ts','features/search/SearchBookProjection.ts','features/search/SearchGateway.ts']);
const sg=new SearchGateway({request:async()=>({data:{sourceId:'s0',books:[{bookId:'https://example.test/valid',title:'鸣龙',author:'关关公子'},{bookId:'https://example.test/bad',title:' ',author:''}]}})});
const searchOutcome=await sg.searchBySource({sourceId:'s0',name:'测试源',enabled:true,category:'novel'},'鸣龙');
assert.equal(searchOutcome.ok,false);
console.log(JSON.stringify({probe:'actual SearchGateway.searchBySource',inputValidBooks:1,inputMalformedBooks:1,outcome:searchOutcome,conclusion:'One malformed record rejects entire source response; no valid sibling returned'}));
