import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
registerHooks({resolve(s,c,n){try{return n(s,c);}catch(e){if(s.startsWith('.')&&!s.endsWith('.ts'))return n(`${s}.ts`,c);throw e;}}});
const root = new URL('../../../', import.meta.url);
const {productionMotionMethods}=await import(new URL('tools/lib/reader-motion-method-probe.mjs',root));
const {BookAcquisitionCoordinator}=await import(new URL('entry/src/main/ets/app/BookAcquisitionCoordinator.ts',root));
const {RemoteReadingFlowGateway}=await import(new URL('entry/src/main/ets/features/reading/RemoteReadingFlowGateway.ts',root));
const calls=[]; const sourceId='s',bookId='b';
const entries=Array.from({length:949},(_,index)=>({index,title:`第${index+1}章`,url:`/${index+1}`,variables:[]}));
const runtime=new BookAcquisitionCoordinator(async(method,p={})=>{
 calls.push(method);
 if(method==='source.list')return{data:{sources:[{sourceId,sourceVersion:'v',enabled:true}]}};
 if(method==='search-book.get')return{data:{book:null}};
 if(method==='cache.book.status')return{data:{sourceId,bookId,tocAvailable:true,chapters:entries.map(e=>({chapterIndex:e.index,title:e.title,url:e.url,variables:{}})),continuationVariables:{}}};
 throw Error('Unexpected '+method);
});
const owner={bookAcquisitions:()=>runtime,request:(...a)=>runtime.request(...a)};
const seed={sourceId,bookId,detailUrl:'b',title:'终宋',author:'作者'};
const session=await runtime.acquireBook(seed);
calls.length=0;
const file=new URL('entry/src/main/ets/pages/Index.ets',root);
const Index=productionMotionMethods(file,['refreshRemoteCatalogNearEnd'],{RemoteReadingFlowGateway,ReaderRuntimeOwner:{current:()=>owner},CATALOG_REFRESH_INTERVAL_MS:600000,DOMAIN:0,hilog:{warn(){}}});
let installed;
const page=Object.assign(new Index(),{remoteCatalogRefreshAt:new Map(),remoteReadingSession:session,detailBook:{...seed,sourceName:'源'},installRemoteReadingSession:s=>{installed=s;},refreshBookshelf(){}});
page.refreshRemoteCatalogNearEnd(session);
const deadline=performance.now()+1000;while(!installed&&performance.now()<deadline)await new Promise(r=>setTimeout(r,1));
assert.equal(installed.entries.length,949);assert.deepEqual(calls,[]);
console.log(JSON.stringify({indexSha256:createHash('sha256').update(readFileSync(file)).digest('hex'),cachedChapters:949,installedChapters:installed.entries.length,coreCalls:calls,refreshMarked:true,conclusion:'near-end refresh returns prepared old catalog without any HTTP/Core call'},null,2));
runtime.close();
