/** Shared Full/Quick Auto Page surface and actor endpoint geometry. */
export const READER_AUTO_PAGE_ACTOR_HOLD_RATIO = 0.14815;
export const READER_AUTO_PAGE_FULL_WIDTH = 364;
export const READER_AUTO_PAGE_FULL_HEIGHT = 736;
export const READER_AUTO_PAGE_QUICK_HEIGHT = 330;
export const READER_AUTO_PAGE_COLLAPSED_SURFACE_WIDTH = 364.896;
export const READER_AUTO_PAGE_COLLAPSED_SURFACE_X = -0.448;
export const READER_AUTO_PAGE_COLLAPSED_SURFACE_Y = 406.443;

export const READER_AUTO_PAGE_FULL_GRABBER_WIDTH = 42;
export const READER_AUTO_PAGE_FULL_GRABBER_HEIGHT = 4;
export const READER_AUTO_PAGE_FULL_GRABBER_X = 160;
export const READER_AUTO_PAGE_FULL_GRABBER_Y = 9;
export const READER_AUTO_PAGE_FULL_HEADER_WIDTH = 336;
export const READER_AUTO_PAGE_FULL_HEADER_X = 14;
export const READER_AUTO_PAGE_FULL_HEADER_Y = 20;
export const READER_AUTO_PAGE_FULL_BODY_WIDTH = 336;
export const READER_AUTO_PAGE_FULL_BODY_HEIGHT = 665;
export const READER_AUTO_PAGE_FULL_BODY_X = 14;
export const READER_AUTO_PAGE_FULL_BODY_Y = 58;
export const READER_AUTO_PAGE_FULL_CONTENT_WIDTH = 314;
export const READER_AUTO_PAGE_FULL_CONTENT_X = 25;
export const READER_AUTO_PAGE_FULL_CONTENT_Y = 69;

// Millivp arithmetic preserves the exact 435.17/285.78 Figma decimals instead
// of depending on binary floating-point addition of the exported decimals.
const READER_AUTO_PAGE_CONTROL_SECTION_MILLIVP = 104390;
const READER_AUTO_PAGE_TIMER_SECTION_MILLIVP = 181390;
const READER_AUTO_PAGE_DETAILS_SECTION_MILLIVP = 149390;
export const READER_AUTO_PAGE_CONTROL_SECTION_HEIGHT =
  READER_AUTO_PAGE_CONTROL_SECTION_MILLIVP / 1000;
export const READER_AUTO_PAGE_TIMER_SECTION_HEIGHT =
  READER_AUTO_PAGE_TIMER_SECTION_MILLIVP / 1000;
export const READER_AUTO_PAGE_DETAILS_SECTION_HEIGHT =
  READER_AUTO_PAGE_DETAILS_SECTION_MILLIVP / 1000;
export const READER_AUTO_PAGE_TIMER_SECTION_Y =
  READER_AUTO_PAGE_CONTROL_SECTION_MILLIVP / 1000;
export const READER_AUTO_PAGE_DETAILS_SECTION_Y =
  (READER_AUTO_PAGE_CONTROL_SECTION_MILLIVP + READER_AUTO_PAGE_TIMER_SECTION_MILLIVP) / 1000;
export const READER_AUTO_PAGE_FULL_CONTENT_HEIGHT =
  (READER_AUTO_PAGE_CONTROL_SECTION_MILLIVP + READER_AUTO_PAGE_TIMER_SECTION_MILLIVP +
    READER_AUTO_PAGE_DETAILS_SECTION_MILLIVP) / 1000;

export const READER_AUTO_PAGE_COLLAPSED_BACK_TRANSLATE_Y = 14;
export const READER_AUTO_PAGE_ADDED_HEADER_TRANSLATE_Y = 18;
export const READER_AUTO_PAGE_ADDED_CONTROL_TITLE_TRANSLATE_Y = 14;
export const READER_AUTO_PAGE_ADDED_TIMER_TRANSLATE_Y = 22;
export const READER_AUTO_PAGE_ADDED_DETAILS_TITLE_TRANSLATE_Y = 18;
export const READER_AUTO_PAGE_ADDED_FOLLOW_HIGHLIGHT_TRANSLATE_Y = 18;
export const READER_AUTO_PAGE_PERSISTENT_PREVIOUS_TRANSLATE_Y = -9.841;
export const READER_AUTO_PAGE_PERSISTENT_NEXT_TRANSLATE_Y = -9.841;
export const READER_AUTO_PAGE_PERSISTENT_PREVIOUS_TRANSLATE_X = -6.45;
export const READER_AUTO_PAGE_PERSISTENT_NEXT_TRANSLATE_X = -36.4;
export const READER_AUTO_PAGE_PERSISTENT_PLAY_LABEL_TRANSLATE_X = -31.492;
export const READER_AUTO_PAGE_PERSISTENT_PLAY_LABEL_TRANSLATE_Y = -2.5;
export const READER_AUTO_PAGE_PERSISTENT_PLAY_TRANSLATE_X = 5.058;
export const READER_AUTO_PAGE_PERSISTENT_PLAY_TRANSLATE_Y = -7.341;
export const READER_AUTO_PAGE_PERSISTENT_STOP_TRANSLATE_X = -33.106;
export const READER_AUTO_PAGE_PERSISTENT_STOP_TRANSLATE_Y = -9.841;
export const READER_AUTO_PAGE_PERSISTENT_SPEED_TRANSLATE_X = -5.45;
export const READER_AUTO_PAGE_PERSISTENT_SPEED_TRANSLATE_Y = -208.623;

export const READER_AUTO_PAGE_EXPANDED_CHAPTER_WIDTH = 72;
export const READER_AUTO_PAGE_COLLAPSED_CHAPTER_WIDTH = 62;
export const READER_AUTO_PAGE_EXPANDED_PLAY_WIDTH = 95;
export const READER_AUTO_PAGE_COLLAPSED_PLAY_WIDTH = 32;
export const READER_AUTO_PAGE_EXPANDED_PLAY_HEIGHT = 52;
export const READER_AUTO_PAGE_COLLAPSED_PLAY_HEIGHT = 32;
export const READER_AUTO_PAGE_EXPANDED_SPEED_WIDTH = 306;
export const READER_AUTO_PAGE_COLLAPSED_SPEED_WIDTH = 264;
export const READER_AUTO_PAGE_EXPANDED_SPEED_HEIGHT = 64;
export const READER_AUTO_PAGE_COLLAPSED_SPEED_HEIGHT = 32;
