// gen_contracts.mjs — generate ArkTS contract bindings + color.json from Reader UI Contract fixtures.
// Idempotent: re-run produces identical output. Safe to re-run whenever contracts change.
//
// Source (read-only): ../Reader UI/contracts/fixtures/{token,route,motion,motion-policy}.json
//   (override with READER_UI_CONTRACTS env var pointing at the fixtures dir)
// Output:
//   entry/src/main/ets/contract/generated/{ColorTokens,DimensionTokens,TextConstraintTokens,TypeTokens,MotionTokens,ShadowTokens,RouteTable,MotionSpecTable,MotionPolicyTable}.ets
//   entry/src/main/resources/base/element/color.json
//   entry/src/main/resources/dark/element/color.json
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

// ── Locate contracts fixtures dir ──────────────────────────────────────────
function resolveContractsDir() {
  const candidates = [
    process.env.READER_UI_CONTRACTS,
    path.resolve(__dirname, '../../Reader UI/contracts/fixtures'),
    path.resolve(REPO_ROOT, '../Reader UI/contracts/fixtures'),
  ].filter(Boolean);
  for (const c of candidates) {
    if (fs.existsSync(path.join(c, 'token.fixtures.json'))) return c;
  }
  console.error('ERROR: could not locate Reader UI contract fixtures dir.');
  console.error('Set READER_UI_CONTRACTS=<path-to>/Reader UI/contracts/fixtures');
  process.exit(1);
}
const CONTRACTS_DIR = resolveContractsDir();
const OUT_ETS = path.resolve(REPO_ROOT, 'entry/src/main/ets/contract/generated');
const OUT_RES_BASE = path.resolve(REPO_ROOT, 'entry/src/main/resources/base/element');
const OUT_RES_DARK = path.resolve(REPO_ROOT, 'entry/src/main/resources/dark/element');

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(CONTRACTS_DIR, name), 'utf8'));
}
const TOKENS = readJson('token.fixtures.json');
const ROUTES = readJson('route.fixtures.json');
const MOTIONS = readJson('motion.fixtures.json');
const POLICIES = readJson('motion-policy.fixtures.json');

function ensureDir(d) { fs.mkdirSync(d, { recursive: true }); }
ensureDir(OUT_ETS);
ensureDir(OUT_RES_BASE);
ensureDir(OUT_RES_DARK);

const HEADER = '// GENERATED by scripts/gen_contracts.mjs — DO NOT EDIT BY HAND.\n// Source: Reader UI/contracts/fixtures/*.json (read-only contract).\n// Re-run `npm run gen:contracts` after any contract change.\n';

// ── Helpers ───────────────────────────────────────────────────────────────
function esc(s) { return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }

// Convert a token name suffix to camelCase: "paper-bright" -> "paperBright"
function camel(suffix) {
  return suffix.split('-').map((p, i) => i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function stripPrefix(name, prefix) {
  if (name.startsWith(prefix)) return name.slice(prefix.length);
  return name;
}

// Parse a token value into ARGB #AARRGGBB (ArkUI color.json byte order).
function toArgb(value) {
  const v = value.trim();
  const hexMatch = v.match(/^#([0-9a-fA-F]{6})$/);
  if (hexMatch) return '#FF' + hexMatch[1].toUpperCase();
  const hex8Match = v.match(/^#([0-9a-fA-F]{8})$/);
  if (hex8Match) return '#' + hex8Match[1].toUpperCase();
  const rgbaMatch = v.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([0-9.]+)\s*)?\)$/);
  if (rgbaMatch) {
    const r = parseInt(rgbaMatch[1], 10);
    const g = parseInt(rgbaMatch[2], 10);
    const b = parseInt(rgbaMatch[3], 10);
    const a = rgbaMatch[4] !== undefined ? parseFloat(rgbaMatch[4]) : 1;
    const aa = Math.round(a * 255);
    const h = (n) => n.toString(16).padStart(2, '0').toUpperCase();
    return '#' + h(aa) + h(r) + h(g) + h(b);
  }
  throw new Error(`Cannot parse color value: ${value}`);
}

// Parse "Npx" / "Nms" / "N" -> number (strips px or ms unit)
function toPxNumber(value) {
  const m = value.match(/^(-?[0-9.]+)\s*(?:px|ms)?$/);
  if (m) return Number(m[1]);
  const n = Number(value);
  if (!Number.isNaN(n)) return n;
  throw new Error(`Cannot parse numeric token value: ${value}`);
}

// snake_case name for color.json: --reader-ds-color-paper -> reader_ds_color_paper
function snakeArg(name) {
  return name.replace(/^--/, '').replace(/-/g, '_');
}

// ── Token partitioning ────────────────────────────────────────────────────
const byCat = (cat) => TOKENS.filter((t) => t.category === cat && t.deprecated !== true);
const COLORS = byCat('color');
const SPACING = byCat('spacing');
const SIZE = byCat('size');
const RADIUS = byCat('radius');
const ELEVATION = byCat('elevation');
const ZINDEX = byCat('z-index');
const TEXT_CONSTRAINT = byCat('text-constraint');
const TYPE = byCat('type');
const FONT = byCat('font');
const MOTION_DUR = byCat('motion-duration');
const MOTION_EASE = byCat('motion-easing');
const SHADOW = byCat('shadow');

// ── ColorTokens.ets ───────────────────────────────────────────────────────
function genColorTokens() {
  const lines = COLORS.map((t) => {
    const suffix = stripPrefix(t.name, '--reader-ds-color-');
    return `  static readonly ${camel(suffix)}: string = '${toArgb(t.value)}';`;
  });
  return `${HEADER}\nexport class ColorTokens {\n${lines.join('\n')}\n}\n`;
}

// ── color.json (base + dark) ──────────────────────────────────────────────
function genColorJson() {
  const paperArgb = toArgb(COLORS.find((c) => c.name === '--reader-ds-color-paper').value);
  const entries = [
    { name: 'start_window_background', value: paperArgb },
    ...COLORS.map((t) => ({ name: snakeArg(t.name), value: toArgb(t.value) })),
  ];
  // dark = base in Phase 1 (contract has no dark variants yet)
  const body = JSON.stringify({ color: entries }, null, 2) + '\n';
  return { base: body, dark: body };
}

// ── DimensionTokens.ets ───────────────────────────────────────────────────
function genClassFor(category, prefix, valueFn) {
  const lines = category.map((t) => {
    const suffix = stripPrefix(t.name, prefix);
    return `  static readonly ${camel(suffix)}: number = ${valueFn(t.value)};`;
  });
  return lines.join('\n');
}
function genDimensionTokens() {
  const spacing = genClassFor(SPACING, '--reader-ds-space-', toPxNumber);
  const size = genClassFor(SIZE, '--reader-ds-size-', toPxNumber);
  const radius = genClassFor(RADIUS, '--reader-ds-radius-', toPxNumber);
  const elevation = genClassFor(ELEVATION, '--reader-ds-elevation-', toPxNumber);
  const zindex = genClassFor(ZINDEX, '--reader-ds-z-', toPxNumber);
  return `${HEADER}\nexport class SpacingTokens {\n${spacing}\n}\n\nexport class SizeTokens {\n${size}\n}\n\nexport class RadiusTokens {\n${radius}\n}\n\nexport class ElevationTokens {\n${elevation}\n}\n\nexport class ZIndexTokens {\n${zindex}\n}\n`;
}

// ── TextConstraintTokens.ets ──────────────────────────────────────────────
function genTextConstraintTokens() {
  const lines = TEXT_CONSTRAINT.map((t) => {
    const suffix = stripPrefix(t.name, '--reader-ds-text-');
    const v = t.value.trim();
    if (/^\d+$/.test(v)) return `  static readonly ${camel(suffix)}: number = ${v};`;
    return `  static readonly ${camel(suffix)}: string = '${esc(v)}';`;
  });
  return `${HEADER}\nexport class TextConstraintTokens {\n${lines.join('\n')}\n}\n`;
}

// ── TypeTokens.ets ────────────────────────────────────────────────────────
function genTypeTokens() {
  const typeLines = TYPE.map((t) => {
    const suffix = stripPrefix(t.name, '--reader-ds-type-');
    return `  static readonly ${camel(suffix)}: number = ${toPxNumber(t.value)};`;
  });
  // Font tokens are iOS-oriented in the contract; map to HarmonyOS-available stacks.
  const fontLines = [
    `  static readonly sans: string = '"HarmonyOS Sans", "PingFang SC", "Microsoft YaHei", sans-serif';`,
    `  static readonly serif: string = '"Noto Serif CJK SC", "Source Han Serif SC", serif';`,
  ];
  return `${HEADER}\nexport class TypeTokens {\n${typeLines.join('\n')}\n}\n\nexport class FontTokens {\n${fontLines.join('\n')}\n}\n`;
}

// ── MotionTokens.ets ─────────────────────────────────────────────────────
function genMotionTokens() {
  const durLines = MOTION_DUR.map((t) => {
    const suffix = stripPrefix(t.name, '--reader-ds-motion-duration-');
    return `  static readonly ${camel(suffix)}: number = ${toPxNumber(t.value)};`;
  });
  const easeLines = MOTION_EASE.map((t) => {
    const suffix = stripPrefix(t.name, '--reader-ds-motion-easing-');
    return `  static readonly ${camel(suffix)}: string = '${esc(t.value)}';`;
  });
  return `${HEADER}\nexport class MotionDurationTokens {\n${durLines.join('\n')}\n}\n\nexport class MotionEasingTokens {\n${easeLines.join('\n')}\n}\n`;
}

// ── ShadowTokens.ets ──────────────────────────────────────────────────────
function genShadowTokens() {
  const lines = SHADOW.map((t) => {
    const suffix = stripPrefix(t.name, '--reader-ds-shadow-');
    return `  static readonly ${camel(suffix)}: string = '${esc(t.value)}';`;
  });
  return `${HEADER}\nexport class ShadowTokens {\n${lines.join('\n')}\n}\n`;
}

// ── TokenRegistry.ets (full name→value registry for coverage tests) ───────
function genTokenRegistry() {
  const cats = [...new Set(TOKENS.map((t) => t.category))];
  const catUnion = cats.map((c) => `'${c}'`).join(' | ');
  const entries = TOKENS.map((t) =>
    `    { name: '${esc(t.name)}', category: '${esc(t.category)}', value: '${esc(t.value)}' }`);
  return `${HEADER}\nexport type TokenCategory = ${catUnion};\nexport interface TokenEntry { name: string; category: TokenCategory; value: string; }\n\nexport class TokenRegistry {\n  static readonly ALL: TokenEntry[] = [\n${entries.join(',\n')}\n  ];\n\n  static byName(name: string): TokenEntry | undefined {\n    for (const t of TokenRegistry.ALL) {\n      if (t.name === name) return t;\n    }\n    return undefined;\n  }\n\n  static byCategory(category: TokenCategory): TokenEntry[] {\n    return TokenRegistry.ALL.filter((t) => t.category === category);\n  }\n}\n`;
}

// ── RouteTable.ets ────────────────────────────────────────────────────────
function genRouteTable() {
  const ids = ROUTES.map((r) => r.id);
  const idUnion = ids.map((i) => `'${i}'`).join(' | ');
  const shells = [...new Set(ROUTES.map((r) => r.shell))];
  const shellUnion = shells.map((s) => `'${s}'`).join(' | ');
  const shellCases = ROUTES.map((r) => `      case '${r.id}': return '${r.shell}';`).join('\n');
  const mainTabCases = ROUTES.filter((r) => r.mainTab).map((r) => `      case '${r.id}': return '${r.mainTab}';`).join('\n');
  return `${HEADER}\nexport type RouteId = ${idUnion};\nexport type ShellId = ${shellUnion};\n\nexport class RouteTable {\n  static shellOf(id: string): ShellId {\n    switch (id) {\n${shellCases}\n      default: return 'FlowShell';\n    }\n  }\n\n  static mainTabOf(id: string): string | null {\n    switch (id) {\n${mainTabCases}\n      default: return null;\n    }\n  }\n}\n`;
}

// ── MotionSpecTable.ets ──────────────────────────────────────────────────
function genMotionSpecTable() {
  const iface = `export interface MotionSpecTokens { durationToken: string; easingToken: string; }\nexport interface MotionSpec {\n  id: string;\n  durationMs: number;\n  easing: string;\n  implementationKind: string;\n  containerRole: string;\n  operation: string;\n  visualPattern: string;\n  interruptPolicy: string;\n  reducedMotionPolicy: string;\n  tokens: MotionSpecTokens;\n  guardRules: string[];\n}`;
  const specs = MOTIONS.map((m) => {
    const gr = (m.guardRules || []).map((g) => `'${esc(g)}'`).join(', ');
    return `    { id: '${esc(m.id)}', durationMs: ${m.durationMs}, easing: '${esc(m.easing)}', implementationKind: '${esc(m.implementationKind)}', containerRole: '${esc(m.containerRole)}', operation: '${esc(m.operation)}', visualPattern: '${esc(m.visualPattern)}', interruptPolicy: '${esc(m.interruptPolicy)}', reducedMotionPolicy: '${esc(m.reducedMotionPolicy)}', tokens: { durationToken: '${esc(m.tokens.durationToken)}', easingToken: '${esc(m.tokens.easingToken)}' }, guardRules: [${gr}] }`;
  });
  return `${HEADER}\n${iface}\n\nexport class MotionSpecTable {\n  static readonly SPECS: MotionSpec[] = [\n${specs.join(',\n')}\n  ];\n\n  static byId(id: string): MotionSpec | undefined {\n    for (const s of MotionSpecTable.SPECS) {\n      if (s.id === id) return s;\n    }\n    return undefined;\n  }\n}\n`;
}

// ── DemoAliasTokens.ets (demo --fd-* aliases not in contract) ─────────────
// Ported from frontend-demo/styles/00-foundation.css. These capture demo-specific
// values (surface tint, on-primary, radius lg/xl) that have no 1:1 --reader-ds-*
// contract token, so 1:1 demo ports can reference them by name.
function genDemoAliasTokens() {
  const hdr = '// GENERATED by scripts/gen_contracts.mjs — DO NOT EDIT BY HAND.\n// Source: ../Reader UI/frontend-demo/styles/00-foundation.css (--fd-* aliases).\n// NOT contract tokens; demo-specific values needed for 1:1 demo-port fidelity.\n';
  return `${hdr}
export class DemoAliasTokens {
  // Colors (demo --fd-surface / --fd-on-primary; the rest alias --reader-ds-*)
  static readonly surface: string = '#E6FFFCF8';    // rgba(255,252,248,0.9)
  static readonly onPrimary: string = '#FFFFFAF4'; // #fffaf4
  // Shadow colors (demo --fd-soft-shadow / --fd-shadow as rgba; ArkUI shadow takes a color)
  static readonly shadowSoftColor: string = '#1A594632';      // rgba(89,70,50,0.10)
  static readonly shadowElevatedColor: string = '#29594632';   // rgba(89,70,50,0.16)
  // Radius scale (demo --fd-radius-xs/sm/md/lg/xl/pill)
  static readonly radiusXs: number = 4;
  static readonly radiusSm: number = 6;
  static readonly radiusMd: number = 8;
  static readonly radiusLg: number = 12;
  static readonly radiusXl: number = 24;
  static readonly radiusPill: number = 999;
}
`;
}

// ── MotionPolicyTable.ets ─────────────────────────────────────────────────
function genMotionPolicyTable() {
  const real = POLICIES.filter((p) => p && p.id && p.priority !== undefined && p.match && p.motionId);
  real.sort((a, b) => b.priority - a.priority);
  const iface = `export interface MotionPolicyMatch {\n  operation?: string;\n  containerRole?: string;\n  sourceRole?: string;\n  targetRole?: string;\n  reducedMotion?: boolean;\n}\nexport interface MotionPolicy {\n  id: string;\n  priority: number;\n  match: MotionPolicyMatch;\n  motionId: string;\n}`;
  const policies = real.map((p) => {
    const m = p.match;
    const parts = [];
    if (m.operation !== undefined) parts.push(`operation: '${esc(m.operation)}'`);
    if (m.containerRole !== undefined) parts.push(`containerRole: '${esc(m.containerRole)}'`);
    if (m.sourceRole !== undefined) parts.push(`sourceRole: '${esc(m.sourceRole)}'`);
    if (m.targetRole !== undefined) parts.push(`targetRole: '${esc(m.targetRole)}'`);
    if (m.reducedMotion !== undefined) parts.push(`reducedMotion: ${m.reducedMotion}`);
    return `    { id: '${esc(p.id)}', priority: ${p.priority}, match: { ${parts.join(', ')} }, motionId: '${esc(p.motionId)}' }`;
  });
  return `${HEADER}\n${iface}\n\nexport class MotionPolicyTable {\n  static readonly POLICIES: MotionPolicy[] = [\n${policies.join(',\n')}\n  ];\n}\n`;
}

// ── Write all ─────────────────────────────────────────────────────────────
function writeEts(name, content) {
  fs.writeFileSync(path.join(OUT_ETS, name), content);
  console.log(`  wrote entry/src/main/ets/contract/generated/${name}`);
}
const colorJson = genColorJson();

writeEts('ColorTokens.ets', genColorTokens());
writeEts('DimensionTokens.ets', genDimensionTokens());
writeEts('TextConstraintTokens.ets', genTextConstraintTokens());
writeEts('TypeTokens.ets', genTypeTokens());
writeEts('MotionTokens.ets', genMotionTokens());
writeEts('ShadowTokens.ets', genShadowTokens());
writeEts('TokenRegistry.ets', genTokenRegistry());
writeEts('RouteTable.ets', genRouteTable());
writeEts('MotionSpecTable.ets', genMotionSpecTable());
writeEts('MotionPolicyTable.ets', genMotionPolicyTable());
writeEts('DemoAliasTokens.ets', genDemoAliasTokens());

fs.writeFileSync(path.join(OUT_RES_BASE, 'color.json'), colorJson.base);
console.log('  wrote entry/src/main/resources/base/element/color.json');
fs.writeFileSync(path.join(OUT_RES_DARK, 'color.json'), colorJson.dark);
console.log('  wrote entry/src/main/resources/dark/element/color.json');

console.log(`\nDone. Contracts: ${CONTRACTS_DIR}`);
console.log(`Tokens: ${TOKENS.length} | Routes: ${ROUTES.length} | Motions: ${MOTIONS.length} | Policies: ${POLICIES.filter((p) => p && p.id).length}`);
