"""Freeze existing encoded fixtures + independent Pillow pixels for the DEBUG HAP pilot.
Requires Pillow; no Reader production transform is imported or reproduced here.
"""
from pathlib import Path
import hashlib, json, shutil
from PIL import Image, ImageOps
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'entry/src/main/resources/rawfile/manga-platform-probe-v1'
OUT.mkdir(parents=True, exist_ok=True)
def sha(b): return hashlib.sha256(b).hexdigest()
def put(name, data):
    (OUT / name).write_bytes(data)
    return sha(data)
cases = []
source = ROOT / 'tools/fixtures/manga-orientation'
original = json.loads((source / 'goldens.json').read_text())
for item in original['cases']:
    encoded = (source / item['file']).read_bytes()
    assert sha(encoded) == item['sha256']
    with Image.open(source / item['file']) as im:
        normalized = ImageOps.exif_transpose(im).convert('RGBA')
        expected = normalized.tobytes()
        normalized.thumbnail((2048, 2048))
        preview_width, preview_height = normalized.size
    assert sha(expected) == item['outputSha256'], 'upstream golden drift: ' + item['file']
    name = item['file']; pixels = name + '.rgba'
    cases.append(dict(id=name, file=name, sha256=put(name, encoded), expectedFile=pixels,
        expectedSha256=put(pixels, expected), width=item['outputWidth'], height=item['outputHeight'],
        orientation=item['orientation'], lossy=name.endswith('.jpg'), previewWidth=preview_width, previewHeight=preview_height))
graphics = ROOT / 'tools/fixtures/manga-graphics'
for name in ['input.png', 'plan.json', 'expected-rgba.bin']:
    put('graphics-' + name, (graphics / name).read_bytes())
manifest = dict(schemaVersion=1, generator='Pillow '+Image.__version__+' ImageOps.exif_transpose; exact match against existing Pillow 11.3 goldens', cases=cases,
    graphics=dict(file='graphics-input.png', sha256=sha((graphics/'input.png').read_bytes()),
        planFile='graphics-plan.json', planSha256=sha((graphics/'plan.json').read_bytes()),
        expectedFile='graphics-expected-rgba.bin', expectedSha256=sha((graphics/'expected-rgba.bin').read_bytes()),width=8,height=103))
put('manifest.json', (json.dumps(manifest, ensure_ascii=False, indent=2)+'\n').encode())
prefix='''// Generated by tools/generate-manga-platform-fixtures.py. Fixed DEBUG-only inputs.
export interface MangaPlatformFixture {
  id: string; file: string; sha256: string; expectedFile: string; expectedSha256: string;
  width: number; height: number; orientation: number; lossy: boolean; previewWidth: number; previewHeight: number;
}
export const MANGA_PLATFORM_FIXTURES: MangaPlatformFixture[] = '''
(ROOT/'entry/src/main/ets/app/MangaPlatformFixtures.ts').write_text(prefix+json.dumps(cases,ensure_ascii=False,indent=2)+';\n'+
 'export interface MangaPlatformGraphicsFixture { file:string; sha256:string; planFile:string; planSha256:string; expectedFile:string; expectedSha256:string; width:number; height:number; }\nexport const MANGA_PLATFORM_GRAPHICS: MangaPlatformGraphicsFixture = '+json.dumps(manifest['graphics'],indent=2)+';\n')
print(json.dumps(dict(cases=len(cases),files=len(list(OUT.iterdir())),bytes=sum(p.stat().st_size for p in OUT.iterdir()),generator=manifest['generator'])))
